services:
  - type: web
    name: react-native-web
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./web-build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
